{

  inputs.nixpkgs.url = github:nixos/nixpkgs/nixos-22.11;

  inputs.haskell-gi.url = github:haskell-gi/haskell-gi;
  inputs.haskell-gi.flake = false;

  outputs = inputs:
    let
      system = "x86_64-linux";
      pkgs = import inputs.nixpkgs { inherit system; };

      inherit (pkgs) lib haskell;
      hlib = haskell.lib;

      haskPkgs = haskell.packages.ghc924.extend (
        hself: hsuper:
        let
          attrs = hlib.packageSourceOverrides (lib.filesystem.haskellPathsInDir ./.) hself hsuper;
        in
          attrs // {
            gi-arrow = hlib.addPkgconfigDepends
              attrs.gi-arrow
              [ pkgs.arrow-cpp pkgs.pcre2];
          }
      );

      devShell = haskPkgs.shellFor {
        packages = hp: [ hp.gi-arrow ];
        #HASKELL_GI_GIR_SEARCH_PATH = "${pkgs.arrow-glib}/share/gir-1.0";
        #HASKELL_GI_TYPELIB_SEARCH_PATH = "${pkgs.arrow-glib}/lib/girepository-1.0";
        buildInputs = [pkgs.libgit2-glib];
      };

      haskell-gi-build-tools = haskPkgs.callCabal2nix "haskell-gi-build-tools" "${inputs.haskell-gi}/bindings" {};

      generate-code =
        let

          pkg-info = {
            name = "gi-arrow";
            version = "9.0";
            description = "Bindings for arrow; autogenerated by haskell-gi.";
            synopsis = "arrow bindings";
            author = null;
            girName = "Arrow";
            girVersion = "1.0";
            girOverrides = null;
            baseVersion = "base >= 4.7 && <5";
            distributionPackages = {
              fedora = [];
              ubuntu = [];
            };
            giDepends = [
              "gi-gio == 2.0.*"
              "gi-gobject == 2.0.*"
              "gi-glib == 2.0.*"
            ];
            pkgconfigDepends = "arrow-glib";
          };

        in
          pkgs.writeShellApplication {
            name = "gen-code.sh";
            runtimeInputs = with pkgs; [
              coreutils
              jq
              cabal-install
              haskell-gi-build-tools
              arrow-glib
              arrow-cpp
              pkg-config
            ];

            text = ''
              export HASKELL_GI_GIR_SEARCH_PATH="${pkgs.arrow-glib}/share/gir-1.0";
              export HASKELL_GI_TYPELIB_SEARCH_PATH="${pkgs.arrow-glib}/lib/girepository-1.0";

              mkdir ./gi-arrow

              cat <<EOF | jq | tee ./gi-arrow/pkg.info | jq -C
              ${__toJSON pkg-info}
              EOF

              ${haskell-gi-build-tools}/bin/genBuildInfo ./gi-arrow

              cd ./gi-arrow
              cabal build --only-configure
              cabal clean
            '';
          };

    in

      {

        inherit pkgs haskPkgs haskell-gi-build-tools;

        devShells.${system}.default = devShell;

        packages.${system}.default = haskell-gi-build-tools;

        apps.${system}.default = {
          type = "app";
          program = "${generate-code}/bin/gen-code.sh";
        };

      };
  
}
