name:                hs-arrow
version:             0.1.0.0
github:              "stephenpascoe/hs-arrow"
license:             BSD3
author:              "Stephen Pascoe"
maintainer:          "stephen.pascoe@lirico.co.uk"
copyright:           "2018 Stephen Pascoe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stephenpascoe/hs-arrow#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - gi-arrow >= 0.0.1 && < 0.1

executables:
  hs-arrow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-arrow

tests:
  hs-arrow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-arrow
